import os
import zipfile
import logging
import subprocess

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def create_release_build(root_dir: str):
    logging.info("Compiling launcher executable...")
    try:
        subprocess.run(["pyinstaller", "AetherVault.spec", "--clean", "-y", "--distpath", "."], cwd=root_dir, check=True)
    except Exception as e:
        logging.error(f"Failed to compile launcher: {e}")
        return

    dist_dir = os.path.join(root_dir, "dist")
    os.makedirs(dist_dir, exist_ok=True)
    
    zip_path = os.path.join(dist_dir, "AIManager_Release.zip")
    logging.info(f"Assembling pristine release build: {zip_path}")

    # Files and folders to strictly ignore when packaging
    ignore_dirs = {
        "bin", "packages", "dist", ".git", "__pycache__", "cache", ".gemini",
        ".venv", ".pytest_cache", ".tests", "node_modules", ".github", "build",
        ".agent", ".agents", "Workflows"
    }
    ignore_files = {
        "metadata.sqlite", "build.py", "AIManager_Release.zip",
        ".coverage", "test_results.txt", "merged_walkthroughs.md",
        "merged_walkthroughs.txt", "pending_work.md", "collect_docs.py",
        "requirements-qa.txt", "start_manager.bat", "start_manager.sh",
        "tray_launcher.py", "AetherVault.spec", "agents.md",
        "session-summary.md", "README.md", "settings.json",
        "e2e.txt", "e2e_results.txt", "e2e_results_utf8.txt", "funcs.txt"
    }
    
    # We will explicitly add Global_Vault subdirectories manually as empty stubs
    ignore_dirs.add("Global_Vault")
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Walk and add core source files
        for root, dirs, files in os.walk(root_dir):
            # Prune ignored directories in-place so os.walk ignores them
            dirs[:] = [d for d in dirs if d not in ignore_dirs]
            
            for file in files:
                if file in ignore_files or file.endswith(".pyc") or file.endswith(".log") or file.endswith(".bat") or file.endswith(".sh"):
                    continue
                
                # Exclude test files, dev scripts, and repo metadata
                if file.startswith("test_") or file.endswith("_test.py") or file.startswith("check_") or file in (
                    "download_test_models.py", "launch_and_test.py", "restart_backend.py", "tools_dl.py",
                    "fix_links.py", ".gitignore", ".gitmodules"
                ):
                    continue
                
                # Exclude any stale executables (like the old AetherVault.exe)
                if file.endswith(".exe") and file != "Local AI Tool.exe":
                    continue
                    
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, root_dir)
                zipf.write(file_path, arcname)
                
        # Manually add the Global Vault skeleton layout
        vault_folders = [
            "Global_Vault/checkpoints/",
            "Global_Vault/loras/",
            "Global_Vault/vaes/",
            "Global_Vault/controlnet/",
            "Global_Vault/unet/",
            "Global_Vault/clip/",
            "Global_Vault/upscaler/",
            "Global_Vault/motion/",
        ]
        
        for folder in vault_folders:
            zipInfo = zipfile.ZipInfo(folder)
            zipf.writestr(zipInfo, "")
            
        # Add the .manager_ignore token
        zipf.writestr("Global_Vault/.manager_ignore", "Autogenerated Vault Marker")
            
    logging.info("Build payload compiled successfully.")
    
if __name__ == "__main__":
    rood_path = os.path.dirname(os.path.abspath(__file__))
    create_release_build(rood_path)
